easy_admin:
    entities:
        Page:
            class: App\Entity\Page
        Block:
            class: App\Entity\Block
        Txt:
            class: App\Entity\Txt
        Language:
            class: App\Entity\Language
        Template:
            class: App\Entity\Template
            form:
                fields:
                    - { property: 'core', type: 'fos_ckeditor' }
