easy_admin:
    entities:
        Page:
            class: App\Entity\Page
            form:
                fields:
                    - { property: 'name'}
                    - { property: 'blocks', type: 'collection', type_options:{ entry_type: App\Form\BlockType , allow_delete: true , allow_add: true , by_reference: false }}
                    - { property: 'txts', type: 'collection', type_options:{ entry_type: App\Form\TxtType , allow_delete: true , allow_add: true , by_reference: false }}
                    - { property: 'template'}
        Block:
            class: App\Entity\Block
            form:
                fields:
                    - { property: 'name', type: }
                    - { property: 'txts'}
                    - { property: 'template'}
        Txt:
            class: App\Entity\Txt
            form:
                fields:
                    - { property: 'name',}
                    - { property: 'language'}
                    - { property: 'txt'}
        Language:
            class: App\Entity\Language
            form:
                fields:
                    - { property: 'name', type: }
                    - { property: 'shortName'}
        Template:
            class: App\Entity\Template
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'core' }
                    - { property: 'tmpBefor' }
                    - { property: 'tmpAfter' }